[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "demos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
    "pygame-ce",
    "numpy",
]

[project.scripts]
tomdemos = "tomdemos.main:main"

[tool.setuptools.packages.find]
include = ["tomdemos*"]
